---
# tasks file for fail2ban
- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ fail2ban_packages }}"

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ fail2ban_service }}"
  when:
    - ansible_virtualization_type != "docker"
