---
# tasks file for fail2ban
- name: install fail2ban
  package:
    name: "{{ fail2ban_pacakges }}"
    state: "{{ fail2ban_package_state }}"

- name: start and enable fail2ban
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ fail2ban_service }}"
  when:
    - ansible_virtualization_type != "docker"
