---
# handlers file for fail2ban
- name: restart fail2ban
  service:
    name: "{{ fail2ban_service }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker" or fail2ban_ignore_docker
