---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: fail2ban-archlinux
    image: base/archlinux
  - name: fail2ban-alpine-3.6
    image: alpine:3.6
  - name: fail2ban-alpine-3.7
    image: alpine:3.7
  - name: fail2ban-centos-6
    image: centos:6
  - name: fail2ban-centos-7
    image: centos:7
  - name: fail2ban-debian-jessie
    image: debian:jessie
  - name: fail2ban-debian-stretch
    image: debian:stretch
  - name: fail2ban-debian-buster
    image: debian:buster
  - name: fail2ban-fedora-27
    image: fedora:27
  - name: fail2ban-fedora-28
    image: fedora:28
  - name: fail2ban-opensuse-42.2
    image: opensuse:42.2
  - name: fail2ban-opensuse-42.3
    image: opensuse:42.3
  - name: fail2ban-ubuntu-artful
    image: ubuntu:artful
  - name: fail2ban-ubuntu-bionic
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: 'flake8'
